### ISSUE TITLE
Brick studio issue

### ISSUE THREAD

**Issue by bobbyllx** [BrickSchema/brick-studio#1]
Dear Shreyas,

Thank you for your contribution of brick studio.
I am trying it and found some issues to clarify with you.

1 local storage load failure.
I can input the web link. But for a local . ttl.  It will hang with "analyzing".
2 for editor
After edition, I could not find the "download" button to save a local copy.

BTW, I am using Windows 10 with chrome. Is it due to user privilege?

BR, 
Bob

**Comment by shreyasnagare** [comment]
@bobbyllx Thanks for contributing!

1. I have added support for authoring local files.
2. I have a few questions for you. The answers will help me figure out the actual problem.

### Questions:
1. Were you able to see all the buttons (including the 'Download' button) when you first loaded a TTL file? (before adding anything)
2. Were you able to see the other buttons ('Export Analysis', 'Expand All', etc) after you added new information to the file? If yes, are these buttons very very close to the bottom edge of your display?
3. What is your screen resolution?

**Comment by bobbyllx** [comment]
Hi Shreyas,

Thank you for your reply.

My laptop resolution is 1920*1080. I cound not see the download button even
in the viewer before doing edition. I could see Expand all but no "export
analysis". Let me change the solution to try again.

The other question, how to open a local TTL?

BR,
Bob

**Comment by bobbyllx** [comment]
Hi Shreyas,

After increasing the resolution, I could see the "export analysis" and "
Download" button.  Thanks!

Does  brick studio supports opening local TTL file? Currently it hangs
"Fetching..." Even if I run Brick Studio locally.

BR,
Bob

**Comment by shreyasnagare** [comment]
@bobbyllx You should see a button right below the text input field. If you don't see it, try pulling in the latest changes and then hard reload BrickStudio on Chrome.

Hard reloading on Windows:
`SHIFT` + `CTRL` + `R`
or
`SHIFT` + Reload webpage button

I've created a [video](https://youtu.be/V96_t9Vkjlw) that might help.

**Comment by bobbyllx** [comment]
Hi Shreyas,

Thank you so much for your help.  Now I am using the new version tool.
Really appreciate!


BR,
Bob
