### ISSUE TITLE
Nodes are not displayed

### ISSUE THREAD

**Issue by charlie42** [BrickSchema/brick-studio#2]
I tried to both load a local file and open from URL, both from local instance (node) and the live demo. In the console I can see `force-graph loading 6174 nodes 8392 links`, but I can only see the background and no nodes displayed even after an hour.

**Comment by shreyasnagare** [comment]
Thanks for posting the issue! Try clicking on the `Expand All` button and let me know if this changes anything.

**Comment by charlie42** [comment]
Thanks for the quick response, it worked!
